### ISSUE TITLE
Création de la BDD et de son interface

### ISSUE THREAD

**Issue by arthur2klein** [arthur2klein/pfe_messagerie#1]
Création d'une classe Service_bdd contenant les méthodes suivantes:
- rename_group(group_id, new_name),
- remove_user_from_group(group_id, user_id),
- add_user_to_group(user_id, group_id)
- create_group() -> group,
- get_group(group_id) -> group,
- get_groups_user(user_id) -> list[group],
- create_message(message) -> message_id,
- create_message_with_medias(message, list[medias]),
- get_message_user_iterator(user_id) -> message_iterator,
- get_medias_message(message_id) -> list[medias],
- get_message(message_id),
- delete_message(message_id),
- create_media(media) -> media_id,
- get_media(media_id) -> media,
- delete_media(media_id),
- create_message(message) -> message_id,
- create_user(user) -> user_id,
- delete_user(user_id),
- get_user(user_id),
- get_user_auth(auth_id) -> user,
- get_user_email(email) -> user,
- set_user(user_id, user),
- get_all_users() -> list[user].

Ce service accèdera à une base de données contenant les informations suivantes:
User: id, name, first_name, email, join_date, auth_id,
Group: id, name,
UserInGroup: id, user_id, group_id,
Media: id, type, link, message_id,
Message: id, content, sender_id, receiver_group_id, date.

**Comment by arthur2klein** [comment]
Concernant la sécuriasation:
- mettre en place des politiques de contrôle d'accès: adopter des politiques basées sur les rôles (RBAC) ou les attributs (ABAC) pour contrôler l'accès au ressources,
- garantif l'intégrité des données: employer des mécanismes de somme de contrôle et de signature numérique pour les données en stockage et en transit,
- assurer la confidentialité: chiffrer les données en transit (TLS) et au repos (AES), appliquer le principe de moindre privilège pour l'accès aux données,
- journaliser les logs: établir une journalisation détaillée pour toutes actions critiques

Chiffrement des Données au Repos : Utilisez des algorithmes de chiffrement robustes pour protéger les données stockées dans la base de données.
Chiffrement des Données en Transit : Assurez-vous que les données sont chiffrées lorsqu'elles sont transférées entre la base de données et le client ou d'autres composants.

**Comment by Rodriguez001** [comment]
Ajouter une methode get_users_in_group(group_id) pour les users d'un groupe
