### ISSUE TITLE
Création du frontend

### ISSUE THREAD

**Issue by arthur2klein** [arthur2klein/pfe_messagerie#5]
En utilisant l'API de #4 , création d'un frontend au choix devant contenir au minimum:
- une page d'accueil,
- une page d'authentification,
- une page d'inscription,
- une page de gestion de profil,
- une page de gestion de groupes,
- une page d'accès au group,
- une page de consultation des messages du group et ajout de nouveaux messages.

**Comment by EmmaDjeufa** [comment]
Bien reçu merci Arthur.
